[build]
target = "index.html"
no_default_features = true
no_sri = true

[watch]
ignore = ["./target", "./dist"]

[serve]
headers = { "Cross-Origin-Opener-Policy" = "same-origin", "Cross-Origin-Embedder-Policy" = "require-corp" }
